[package]
name = "rust-baseball-practice"
version = "0.1.0"
authors = ["Eugine Park <pkeugine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
